/*import { Injectable } from '@angular/core';

@Injectable()
export class ViajesService{
public viajes:Array<Viaje>
constructor(){
  this.viajes = [
    new Viaje('MANZANILLO','004536','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS', 'MINERA PENMONT, S DE L.R. - PENMONT (HERRADURA)', '0152364895764','PEREA HERNANDEZ ELI'),
    new Viaje('SAN LUIS POTOSI','004535','BAG IN BOX CON CIANURO DE SODIO EN BRIQUETAS','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - BASE HERMOSILLO','N/A','MIRANDA TORRES PEDRO'),
    new Viaje('HERMOSILLO','004534','CONTENEDOR VACIO','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - CONTECON MANZANILLO S.A DE C.V','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('HERMOSILLO','004533','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS','MINAS DE ORO NACIONAL - MULATOS','0012365421','ORTEGA HERNANDEZ ANTONIO'),
    new Viaje('MANZANILLO','004532','FLOBIN CON CIANURO DE SODIO EN BRIQUETAS','MINERA PENMONT, S DE L.R. - PENMONT (LIXIVIACION)','00532852289','LEZAMA CASTILLO ARMANDO'),
    new Viaje('SAN LUIS POTOSI','004531','CONTENEDOR VACIO','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - CONTECON MANZANILLO S.A DE C.V','N/A','PEREZ PEREZ JUAN OLEGARIO'),
    new Viaje('HERMOSILLO','004530','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS','DESARROLLOS MINEROS SAN LUIS SA DE CV - DESARROLLOS MINEROS','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('SAN LUIS POTOSI','004529','BAG IN BOX CON CIANURO DE SODIO EN BRIQUETAS','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - BASE HERMOSILLO','N/A','MIRANDA TORRES PEDRO'),
    new Viaje('HERMOSILLO','004528','CONTENEDOR VACIO','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - CONTECON MANZANILLO S.A DE C.V','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('MANZANILLO','004527','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS', 'MINERA PENMONT, S DE L.R. - PENMONT (HERRADURA)', '0152364895764','PEREA HERNANDEZ ELI'),
    new Viaje('SAN LUIS POTOSI','004526','BAG IN BOX CON CIANURO DE SODIO EN BRIQUETAS','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - BASE HERMOSILLO','N/A','MIRANDA TORRES PEDRO'),
    new Viaje('HERMOSILLO','004525','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS','DESARROLLOS MINEROS SAN LUIS SA DE CV - DESARROLLOS MINEROS','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('SAN LUIS POTOSI','004524','BAG IN BOX CON CIANURO DE SODIO EN BRIQUETAS','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - BASE HERMOSILLO','N/A','MIRANDA TORRES PEDRO'),
    new Viaje('HERMOSILLO','004523','CONTENEDOR VACIO','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - CONTECON MANZANILLO S.A DE C.V','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('MANZANILLO','004522','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS', 'MINERA PENMONT, S DE L.R. - PENMONT (HERRADURA)', '0152364895764','PEREA HERNANDEZ ELI'),
    new Viaje('HERMOSILLO','004521','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS','MINAS DE ORO NACIONAL - MULATOS','0012365421','ORTEGA HERNANDEZ ANTONIO'),
    new Viaje('MANZANILLO','004520','FLOBIN CON CIANURO DE SODIO EN BRIQUETAS','MINERA PENMONT, S DE L.R. - PENMONT (LIXIVIACION)','00532852289','LEZAMA CASTILLO ARMANDO'),
    new Viaje('SAN LUIS POTOSI','004519','CONTENEDOR VACIO','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - CONTECON MANZANILLO S.A DE C.V','N/A','PEREZ PEREZ JUAN OLEGARIO'),
    new Viaje('HERMOSILLO','004518','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS','DESARROLLOS MINEROS SAN LUIS SA DE CV - DESARROLLOS MINEROS','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('SAN LUIS POTOSI','004517','BAG IN BOX CON CIANURO DE SODIO EN BRIQUETAS','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - BASE HERMOSILLO','N/A','MIRANDA TORRES PEDRO'),
    new Viaje('HERMOSILLO','004516','CONTENEDOR VACIO','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - CONTECON MANZANILLO S.A DE C.V','N/A','HERNANDEZ TREJO RIGOBERTO'),
    new Viaje('MANZANILLO','004515','ISOTANQUE DE CIANURO DE SODIO EN BRIQUETAS', 'MINERA PENMONT, S DE L.R. - PENMONT (HERRADURA)', '0152364895764','PEREA HERNANDEZ ELI'),
    new Viaje('SAN LUIS POTOSI','004514','BAG IN BOX CON CIANURO DE SODIO EN BRIQUETAS','THE CHEMOURS COMPANY MEXICANA S. DE R.L. - BASE HERMOSILLO','N/A','MIRANDA TORRES PEDRO'),
  ];
}
}
*/
